### ISSUE TITLE
Release binaries

### ISSUE THREAD

**Issue by Madoshakalaka** [holmgr/cargo-sweep#64]
Since most likely this tool will get used in CI, it's really optimal to include built binaries in the releases.

and advise users to download binaries in the following way
`wget -qO- https://github.com/holmgr/cargo-sweep/releases/download/${VERSION}/cargo-sweep-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-`

[trunk](https://github.com/thedodd/trunk) is an excellent reference to the CI setup for prebuilt binaries.

**Comment by Madoshakalaka** [comment]
In the time being, I recommend using the following github action to build the binary and commit to your repo peoriodically or on manual trigger:
```yml
name: Build Cargo Sweep Binary

on:
  schedule:
    # friday noon
    - cron: '0 12 * * 5'
  workflow_dispatch:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: cargo install cargo-sweep
    - uses: actions/checkout@v2
    - name: Transfer Binary
      run: 'mv ~/.cargo/bin/cargo-sweep YOUR/PATH/TO/CI-BIN'
    - name: Commit Binary
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "🤖 build cargo-sweep binary for ci use"
```
